-- Alter Ticket.status enum to include DITOLAK
ALTER TABLE `Ticket`
  MODIFY `status` ENUM('PENDING', 'PROSES', 'SELESAI', 'DIBATALKAN', 'DITOLAK') NOT NULL DEFAULT 'PENDING';

-- Alter AuditLog.eventType enum to include TICKET_REJECTION
ALTER TABLE `AuditLog`
  MODIFY `eventType` ENUM('LOGIN', 'REGISTRATION', 'TICKET_CREATION', 'TICKET_ASSIGNMENT', 'TICKET_COMPLETION', 'TICKET_CANCELLATION', 'TICKET_REJECTION', 'TICKET_RATING', 'USER_SOFT_DELETE', 'ROLE_CHANGE', 'PASSWORD_RESET', 'PASSWORD_CHANGE', 'SETTINGS_CHANGE', 'TEAM_ASSIGNMENT', 'TEAM_REMOVAL') NOT NULL;
