// Shared enums for SIGAP

export enum Role {
  SATKER = 'SATKER',
  BIDTEKKOM = 'BIDTEKKOM',
  PADAL = 'PADAL',
  TEKNISI = 'TEKNISI',
}

export enum TicketStatus {
  PENDING = 'PENDING',
  PROSES = 'PROSES',
  SELESAI = 'SELESAI',
  DIBATALKAN = 'DIBATALKAN',
  DITOLAK = 'DITOLAK',
}

export enum TicketCategory {
  HARDWARE = 'HARDWARE',
  SOFTWARE = 'SOFTWARE',
  JARINGAN = 'JARINGAN',
  EMAIL = 'EMAIL',
  WEBSITE = 'WEBSITE',
  LAINNYA = 'LAINNYA',
}

export enum NotificationType {
  TICKET_CREATED = 'TICKET_CREATED',
  TICKET_ASSIGNED = 'TICKET_ASSIGNED',
  TICKET_COMPLETED = 'TICKET_COMPLETED',
  TICKET_CANCELLED = 'TICKET_CANCELLED',
}

export enum AuditEventType {
  LOGIN = 'LOGIN',
  REGISTRATION = 'REGISTRATION',
  TICKET_CREATION = 'TICKET_CREATION',
  TICKET_ASSIGNMENT = 'TICKET_ASSIGNMENT',
  TICKET_COMPLETION = 'TICKET_COMPLETION',
  TICKET_CANCELLATION = 'TICKET_CANCELLATION',
  TICKET_REJECTION = 'TICKET_REJECTION',
  TICKET_RATING = 'TICKET_RATING',
  USER_SOFT_DELETE = 'USER_SOFT_DELETE',
  ROLE_CHANGE = 'ROLE_CHANGE',
  PASSWORD_RESET = 'PASSWORD_RESET',
  PASSWORD_CHANGE = 'PASSWORD_CHANGE',
  SETTINGS_CHANGE = 'SETTINGS_CHANGE',
  TEAM_ASSIGNMENT = 'TEAM_ASSIGNMENT',
  TEAM_REMOVAL = 'TEAM_REMOVAL',
}